apiVersion: apps/v1
kind: Deployment
metadata:
  name: ady
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ady 
  template:
    metadata:
      labels:
        app: ady
    spec:
      containers: 
        
name: ady
        image: ady
        ports:
containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ady-service
spec:
  type: NodePort
  selector:
    app: ady
  ports:
    
protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000